name: Build

on:
  workflow_dispatch:
    inputs:
      build_config:
        description: 'Build Configuration'
        required: true
        default: 'Release'
        type: choice
        options:
          - Debug
          - Release

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET Framework 4.8
        run: |
          choco install netfx-4.8 -y

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v2
      
      - name: Install TDM-GCC
        run: |
          $fileUrl = "https://github.com/jmeubank/tdm-gcc-src/releases/download/v10.3.0-tdm64-1/gcc-10.3.0-tdm64-1-core.zip"
          $zipPath = "$env:TEMP\gcc-10.3.0-tdm64-1-core.zip"
          $extractPath = "C:\TDM-GCC-64"
          
          Invoke-WebRequest -Uri $fileUrl -OutFile $downloadPath
          if (-Not (Test-Path $zipPath)) {
            Write-Error "Failed to download TDM-GCC ZIP file"
            exit 1
          }

          Write-Host "Extracting TDM-GCC..."
          Expand-Archive -Path $zipPath -DestinationPath $extractPath

          $env:Path += ";$extractPath\bin"

          Write-Host "TDM-GCC installed successfully"
          gcc --version

      - name: Restore NuGet packages
        run: |
          nuget restore MPRISBee.sln

      - name: Build the solution
        run: |
          msbuild MPRISBee.sln /p:Configuration=${{ github.event.inputs.build_config }}
          
      - name: Compile C file
        run: |
          gcc -m32 -masm=intel -shared -mconsole -Wall -Wextra -O2 -o D:\a\mb_MPRISBee\mb_MPRISBee\bin\Release\linux_syscalls.dll D:\a\mb_MPRISBee\mb_MPRISBee\linux_syscalls.c D:\a\mb_MPRISBee\mb_MPRISBee\linux_syscalls.def
