name: Build

on:
  workflow_dispatch:
    inputs:
      build_config:
        description: 'Build Configuration'
        required: true
        default: 'Release'
        type: choice
        options:
          - Debug
          - Release

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET Framework 4.8
        run: |
          # Install .NET Framework 4.8 on the runner
          choco install dotnetframework --version=4.8.0

      - name: Restore NuGet packages
        run: |
          nuget restore YourSolution.sln

      - name: Build the solution
        run: |
          msbuild MPRISBee.sln /p:Configuration=${{ github.event.inputs.build_config }}
