name: Build

on:
  workflow_dispatch:
    inputs:
      build_config:
        description: 'Build Configuration'
        required: true
        default: 'Release'
        type: choice
        options:
          - Debug
          - Release

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET Framework 4.8
        run: |
          choco install netfx-4.8 -y

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1.0.2
        with:
          vs-version: '2022'

      - name: Restore NuGet packages
        run: |
          nuget restore MPRISBee.sln

      - name: Build the solution
        run: |
          msbuild MPRISBee.sln /p:Configuration=${{ github.event.inputs.build_config }}
