name: Build

on:
  workflow_dispatch:
    inputs:
      build_config:
        description: 'Build Configuration'
        required: true
        default: 'Release'
        type: choice
        options:
          - Debug
          - Release

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET Framework 4.8
        run: |
          choco install netfx-4.8 -y

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v2
      
      - name: Install TDM-GCC
        run: |
          Invoke-WebRequest -Uri "https://github.com/jmeubank/tdm-gcc/releases/download/v10.3.0-tdm64-2/tdm64-gcc-10.3.0-2.exe"
          Start-Process -FilePath "tdm64-gcc-10.3.0-2.exe" -ArgumentList "/SILENT" -Wait

      - name: Restore NuGet packages
        run: |
          nuget restore MPRISBee.sln

      - name: Build the solution
        run: |
          msbuild MPRISBee.sln /p:Configuration=${{ github.event.inputs.build_config }}
          
      - name: Compile C file
        run: |
          C:\TDM-GCC-64\bin\gcc.exe -m32 -masm=intel -shared -mconsole -Wall -Wextra -O2 -o D:\a\mb_MPRISBee\mb_MPRISBee\bin\Release\linux_syscalls.dll D:\a\mb_MPRISBee\mb_MPRISBee\linux_syscalls.c D:\a\mb_MPRISBee\mb_MPRISBee\linux_syscalls.def
